SELECT
  CAST(LAST_DAY(DATE(INCOMING_CASE_DT), MONTH) AS STRING ) AS month,
  EXTRACT(YEAR
  FROM
    DATE(INCOMING_CASE_DT)) AS years,
  SUM(USD_INTERACTION_GESTION) AS TOTAL_USD
FROM
  SBOX_CX_BI_ADS_CORE.CX_STUDIO_TABLE_SAMPLE
WHERE
  INCOMING_CASE_DT BETWEEN