SELECT
    NIVEL_3,
    COUNT(*) AS CASES,
    SUM(USD_INTERACTION_GESTION) AS TOTAL_USD
FROM
    SBOX_CX_BI_ADS_CORE.CX_STUDIO_TABLE_SAMPLE
WHERE
    NIVEL_3 IS NOT NULL
  AND INCOMING_CASE_DT BETWEEN