SELECT
    SUM(SURVEYS) AS surveys,
    SUM(PROMOTERS) AS promoter,
    SUM(PASSIVES) AS passives,
    SUM(DETRACTORS) AS detractors
FROM
    SBOX_CX_BI_ADS_CORE.CX_STUDIO_TABLE_SAMPLE
WHERE
    INCOMING_CASE_DT BETWEEN